export const people = {
    instructors: [
        {
            id: 25,
            class: "beg",
            name: "Alice Smith",
            rollno: "snb",
        },
        {
            id: 26,
            class: "Inter",
            name: "Bob Johnson",
            rollno: "ski",
        },
        {
            id: 27,
            class: "beg",
            name: "Cathy Davis",
            rollno: "both",
        },
        {
            id: 28,
            class: "adv",
            name: "David Martinez",
            rollno: "ski",
        },
        {
            id: 29,
            class: "Inter",
            name: "Eva Lewis",
            rollno: "snb",
        },
        {
            id: 30,
            class: "beg",
            name: "Frank Clark",
            rollno: "both",
        },
        {
            id: 31,
            class: "adv",
            name: "Grace Rodz",
            rollno: "ski",
        },
        {
            id: 32,
            class: "Inter",
            name: "Henry Lee",
            rollno: "snb",
        },
        {
            id: 33,
            class: "beg",
            name: "Isabella Walker",
            rollno: "both",
        },
        {
            id: 34,
            class: "adv",
            name: "Jack Hall",
            rollno: "ski",
        },
        {
            id: 35,
            class: "Inter",
            name: "Katie Allen",
            rollno: "snb",
        },
        {
            id: 36,
            class: "beg",
            name: "Liam Young",
            rollno: "both",
        },
        {
            id: 37,
            class: "adv",
            name: "Mia Hernandez",
            rollno: "ski",
        },
        {
            id: 38,
            class: "Inter",
            name: "Nathan King",
            rollno: "snb",
        },
        {
            id: 39,
            class: "beg",
            name: "Olivia Scott",
            rollno: "both",
        },
        {
            id: 40,
            class: "adv",
            name: "Patrick Wright",
            rollno: "ski",
        },
    ],
};
